# This docker compose file is specific to running the annotations app.
version: "3.2"

volumes:
  annotations_storage: {}
  annotations_db: {}

services:
  widgetbuild:
    image: "node:18-alpine"
    volumes:
      - ${PWD}/src:/app
      - type: bind
        source: ./scripts/build-ui-widget.sh
        target: /etc/build-ui-widget.sh
    command: /bin/sh /etc/build-ui-widget.sh
    stop_signal: sigkill

  annotations:
    build:
      context: ./src/annotation/
      dockerfile: Dockerfile
    image: annotations
    environment:
      AZURE_STORAGE_CONNECTION_STRING: ""
      IS_READONLY: "false"
      DATABASE_URL: "sa:Your_password123@annotations_mssql/master?charset=utf8"
      # we need tds_version because of pymssql and datetimes parsing issues
      # pyodbc is even worse
      SQLALCHEMY_URL: "mssql+pymssql://sa:Your_password123@annotations_mssql/master?charset=utf8&tds_version=7.2"
      STORAGE_AZURE_CONNECTIONSTRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://annotations_objstore:10000/devstoreaccount1;"
      STORAGE_AZURE_CONTAINERNAME: "peremages"
    volumes:
      - ./src/annotation:/app
      - ./data/:/data
    ports:
      - "8080:8080"
    env_file:
      - ./src/annotation/.env
    command: /app/devops/run-annotation-api-local.sh
    depends_on:
      - annotations_mssql
      - annotations_objstore
    stop_signal: sigkill

  annotations_mssql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - annotations_db:/var/opt/mssql
    logging:
      driver: none

  annotations_objstore:
    # https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=docker-hub
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000 -l /workspace -d /workspace/debug.log
    volumes:
      - "annotations_storage:/workspace"
    logging:
      driver: none
