"""Initial

Revision ID: 5f1259d1237b
Revises: 
Create Date: 2022-03-10 17:58:32.964365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '5f1259d1237b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
                    sa.Column('anno_id', sa.Integer(), nullable=False),
                    sa.Column('img_id', sa.Integer(), nullable=True),
                    sa.Column('geometry', sa.Text(), nullable=True),
                    sa.Column('annotation', sa.Text(), nullable=True),
                    sa.Column('metadata', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('anno_id')
                    )
    op.create_table('globals',
                    sa.Column('key', sa.String(length=8000), nullable=False),
                    sa.Column('value', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('key')
                    )
    op.create_table('imagecollections',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=True),
                    sa.Column('user_id', sa.String(length=255), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('images',
                    sa.Column('img_id', sa.Integer(), nullable=False),
                    sa.Column('filename', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('img_id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('profile_pic', sa.String(
                        length=2048), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('images')
    op.drop_table('imagecollections')
    op.drop_table('globals')
    op.drop_table('annotations')
    # ### end Alembic commands ###
