"""user scopes

Revision ID: 61f6b345ea73
Revises: 71846ad0c472
Create Date: 2022-12-30 21:29:31.156777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '61f6b345ea73'
down_revision = '71846ad0c472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userscopes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('imagecollection_id', sa.String(length=36), nullable=False),
    sa.Column('access_level', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['imagecollection_id'], ['imagecollections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table("imagecollections") as batch_op:
        batch_op.drop_column('guest_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("imagecollections") as batch_op:
        batch_op.add_column(sa.Column('guest_users', sa.Text(), nullable=True))
    op.drop_table('userscopes')
    # ### end Alembic commands ###
