"""annotation_datetime

Revision ID: 731a761d486d
Revises: b43253ac7d22
Create Date: 2022-05-06 18:16:00.226435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '731a761d486d'
down_revision = 'b43253ac7d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'created_at')
    # ### end Alembic commands ###
