"""imagecollectionsrelationships

Revision ID: c6fcb18c2440
Revises: 24bb4b591ec6
Create Date: 2022-03-23 19:55:40.054944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'c6fcb18c2440'
down_revision = '24bb4b591ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images_to_collections_table',
                    sa.Column('image_id', sa.String(
                        length=36), nullable=False),
                    sa.Column('collection_id', sa.String(
                        length=36), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['collection_id'], ['imagecollections.id'], ),
                    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
                    sa.PrimaryKeyConstraint('image_id', 'collection_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('collection_id', sa.VARCHAR(
        length=36, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_table('images_to_collections_table')
    # ### end Alembic commands ###
