"""image-collections-relations

Revision ID: ccabf4d80f27
Revises: c609790a4801
Create Date: 2022-06-25 13:32:26.505532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'ccabf4d80f27'
down_revision = 'c609790a4801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'annotations', 'images', ['image_id'], ['id'])
    op.create_foreign_key(None, 'images', 'imagecollections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    # ### end Alembic commands ###
