"""image-collections-relations

Revision ID: ccabf4d80f27
Revises: c609790a4801
Create Date: 2022-06-25 13:32:26.505532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'ccabf4d80f27'
down_revision = 'c609790a4801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("annotations") as batch_op:
        batch_op.create_foreign_key('fk_annotations_images', 'images', ['image_id'], ['id'])
    with op.batch_alter_table("images") as batch_op:
        batch_op.create_foreign_key('fk_images_imagecollections', 'imagecollections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("images") as batch_op:
        batch_op.drop_constraint('fk_images_imagecollections', 'images', type_='foreignkey')
    with op.batch_alter_table("annotations") as batch_op:
        batch_op.drop_constraint('fk_annotations_images', 'annotations', type_='foreignkey')
    # ### end Alembic commands ###
